name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Replace with your default branch if not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"  # Adjust the Python version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt includes jupyter-book

      # Step 4: Build Jupyter Book without executing notebooks
      - name: Build Jupyter Book
        run: |
          jupyter-book config sphinx .  # Check for valid Jupyter Book configuration
          jupyter-book build astro-physics --builder html --keep-going

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "_build/html"  # Path where the book is built
